/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.willbe.giftapp.repository;

import com.willbe.giftapp.domain.AppWidget;
import com.willbe.giftapp.domain.AppWidget_;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface AppWidgetRepository extends JpaRepository<AppWidget, Integer> {

    default List<AppWidget> complete(String query, int maxResults) {
        AppWidget probe = new AppWidget();
        probe.setRule(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(AppWidget_.rule.getName(), match -> match.ignoreCase().startsWith());

        Page<AppWidget> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}