/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.willbe.giftapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.willbe.giftapp.domain.User_;
import com.willbe.giftapp.domain.User__;

public interface User_Repository extends JpaRepository<User_, Integer> {

    default List<User_> complete(String query, int maxResults) {
        User_ probe = new User_();
        probe.setFirstName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(User__.firstName.getName(), match -> match.ignoreCase().startsWith());

        Page<User_> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}