/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.willbe.giftapp.domain;

import com.google.common.base.MoreObjects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.IDENTITY;

@Entity
@Table(name = "artifact")
public class Artifact implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Artifact.class.getName());

    // Raw attributes
    private Integer id;
    private String outputPath;

    // Many to one
    private Config_ config;
    private User_ user;
    private App_ app;

    @Override
    public String entityClassName() {
        return Artifact.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Artifact id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [outputPath] ------------------------

    @Size(max = 500)
    @Column(name = "output_path", length = 500)
    public String getOutputPath() {
        return outputPath;
    }

    public void setOutputPath(String outputPath) {
        this.outputPath = outputPath;
    }

    public Artifact outputPath(String outputPath) {
        setOutputPath(outputPath);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Artifact.config ==> Config_.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "config_id", nullable = false)
    @ManyToOne
    public Config_ getConfig() {
        return config;
    }

    /**
     * Set the {@link #config} without adding this Artifact instance on the passed {@link #config}
     */
    public void setConfig(Config_ config) {
        this.config = config;
    }

    public Artifact config(Config_ config) {
        setConfig(config);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Artifact.user ==> User_.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "user_id", nullable = false)
    @ManyToOne
    public User_ getUser() {
        return user;
    }

    /**
     * Set the {@link #user} without adding this Artifact instance on the passed {@link #user}
     */
    public void setUser(User_ user) {
        this.user = user;
    }

    public Artifact user(User_ user) {
        setUser(user);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Artifact.app ==> App_.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "app_id", nullable = false)
    @ManyToOne
    public App_ getApp() {
        return app;
    }

    /**
     * Set the {@link #app} without adding this Artifact instance on the passed {@link #app}
     */
    public void setApp(App_ app) {
        this.app = app;
    }

    public Artifact app(App_ app) {
        setApp(app);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Artifact withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Artifact && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Artifact instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("outputPath", getOutputPath()) //
                .toString();
    }
}