//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import {ModuleWithProviders} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';

import {HomeComponent} from './home.component';

import {PassportListComponent} from './entities/passport/passport-list.component';
import {PassportDetailComponent} from './entities/passport/passport-detail.component';

import {RoleListComponent} from './entities/role/role-list.component';
import {RoleDetailComponent} from './entities/role/role-detail.component';

import {User_ListComponent} from './entities/user_/user_-list.component';
import {User_DetailComponent} from './entities/user_/user_-detail.component';
import {BenchComponent} from "./entities/bench/bench.component";
import {App_DetailComponent} from "./entities/app_/app_-detail.component";

export const routes: Routes = [
    {path: '', component: HomeComponent}
    ,
    {path: 'passport-list', component: PassportListComponent},
    {path: 'passport/:id', component: PassportDetailComponent}
    ,
    {path: 'role-list', component: RoleListComponent},
    {path: 'role/:id', component: RoleDetailComponent}
    ,
    {path: 'user_-list', component: User_ListComponent},
    {path: 'user_/:id', component: User_DetailComponent},
    {path: 'bench/:id', component: BenchComponent},
    {path: 'app_/:id', component: App_DetailComponent},

];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
