//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {App_} from '../app_/app_';

export class AppWidget {
    // Raw attributes
    id : number;
    rule : string;
    userInterface : string;
    // x-to-one
    app : App_;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.rule = json.rule;
            this.userInterface = json.userInterface;

            if (json.app != null) {
                this.app = new App_(json.app);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : AppWidget[] {
        let appWidgets : AppWidget[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                appWidgets.push(new AppWidget(json));
            }
        }
        return appWidgets;
    }
}
