//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import {Injectable} from '@angular/core';
import {Headers, Http, RequestOptions} from '@angular/http';
import {LazyLoadEvent} from 'primeng/primeng';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import {MessageService} from '../../service/message.service';
import {PageRequestByExample, PageResponse} from '../../support/paging';
import {AppWidget} from './appWidget';

@Injectable()
export class AppWidgetService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a AppWidget by id.
     */
    getAppWidget(id : any) : Observable<AppWidget> {
        return this.http.get('/api/appWidgets/' + id)
            .map(response => new AppWidget(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed appWidget.
     */
    update(appWidget : AppWidget) : Observable<AppWidget> {
        let body = JSON.stringify(appWidget);

        return this.http.put('/api/appWidgets/', body, this.options)
            .map(response => new AppWidget(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of AppWidget using the passed
     * appWidget as an example for the search by example facility.
     */
    getPage(appWidget : AppWidget, event : LazyLoadEvent) : Observable<PageResponse<AppWidget>> {
        let req = new PageRequestByExample(appWidget, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/appWidgets/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<AppWidget>(pr.totalPages, pr.totalElements, AppWidget.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by AppWidgetCompleteComponent.
     */
    complete(query : string) : Observable<AppWidget[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/appWidgets/complete', body, this.options)
            .map(response => AppWidget.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an AppWidget by id.
     */
    delete(id : any) {
        return this.http.delete('/api/appWidgets/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }

    saveConfigAndGenApp(appWidgets: AppWidget[]) {
        debugger;
        let body = JSON.stringify(appWidgets);
        return this.http.post('/api/appWidgets/saveConfigAndGenApp', body, this.options)
            .map(response => AppWidget.toArray(response.json()))
            .catch(this.handleError);
    }
}
