//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {MessageService} from '../../service/message.service';
import {AppWidget} from './appWidget';
import {AppWidgetService} from './appWidget.service';
import {App_} from '../app_/app_';

@Component({
    moduleId: module.id,
	templateUrl: 'appWidget-detail.component.html',
	selector: 'appWidget-detail',
})
export class AppWidgetDetailComponent implements OnInit, OnDestroy {
    appWidget : AppWidget;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new AppWidget
    set app(app : App_) {
        this.appWidget = new AppWidget();
        this.appWidget.app = app;
    }

    @Output() onSaveClicked = new EventEmitter<AppWidget>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private appWidgetService: AppWidgetService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for appWidget-detail ' + id);

            if (id === 'new') {
                this.appWidget = new AppWidget();
            } else {
                this.appWidgetService.getAppWidget(id)
                    .subscribe(appWidget => {
                            this.appWidget = appWidget;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoApp() {
        this.router.navigate(['/app_', this.appWidget.app.id]);
    }

    clearApp() {
        this.appWidget.app = null;
    }

    onSave() {
        this.appWidgetService.update(this.appWidget).
            subscribe(
                appWidget => {
                    this.appWidget = appWidget;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.appWidget);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
