//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {App_} from '../app_/app_';

export class AppWidget {
    // Raw attributes
    id: number;
    type: number;
    rule: string;
    // x-to-one
    app: App_;
    inputValue: string;
    selected: boolean;


    constructor(json?: any) {
        if (json != null) {
            this.id = json.id;
            this.type = json.type;
            this.rule = json.rule;

            if (json.app != null) {
                this.app = new App_(json.app);
            }
        }
    }

    // Utils

    static toArray(jsons: any[]): AppWidget[] {
        let appWidgets: AppWidget[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                appWidgets.push(new AppWidget(json));
            }
        }
        return appWidgets;
    }
}
