//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import {Injectable} from '@angular/core';
import {Headers, Http, RequestOptions} from '@angular/http';
import {LazyLoadEvent} from 'primeng/primeng';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import {MessageService} from '../../service/message.service';
import {PageRequestByExample, PageResponse} from '../../support/paging';
import {WidgetConfig} from './widgetConfig';

@Injectable()
export class WidgetConfigService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a WidgetConfig by id.
     */
    getWidgetConfig(id : any) : Observable<WidgetConfig> {
        return this.http.get('/api/widgetConfigs/' + id)
            .map(response => new WidgetConfig(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed widgetConfig.
     */
    update(widgetConfig : WidgetConfig) : Observable<WidgetConfig> {
        let body = JSON.stringify(widgetConfig);

        return this.http.put('/api/widgetConfigs/', body, this.options)
            .map(response => new WidgetConfig(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of WidgetConfig using the passed
     * widgetConfig as an example for the search by example facility.
     */
    getPage(widgetConfig : WidgetConfig, event : LazyLoadEvent) : Observable<PageResponse<WidgetConfig>> {
        let req = new PageRequestByExample(widgetConfig, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/widgetConfigs/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<WidgetConfig>(pr.totalPages, pr.totalElements, WidgetConfig.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by WidgetConfigCompleteComponent.
     */
    complete(query : string) : Observable<WidgetConfig[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/widgetConfigs/complete', body, this.options)
            .map(response => WidgetConfig.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an WidgetConfig by id.
     */
    delete(id : any) {
        return this.http.delete('/api/widgetConfigs/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
