//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Config_} from '../config_/config_';

export class WidgetConfig {
    // Raw attributes
    id : number;
    inputvalue : string;
    // x-to-one
    config : Config_;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.inputvalue = json.inputvalue;

            if (json.config != null) {
                this.config = new Config_(json.config);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : WidgetConfig[] {
        let widgetConfigs : WidgetConfig[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                widgetConfigs.push(new WidgetConfig(json));
            }
        }
        return widgetConfigs;
    }
}
