//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {MessageService} from '../../service/message.service';
import {WidgetConfig} from './widgetConfig';
import {WidgetConfigService} from './widgetConfig.service';
import {Config_} from '../config_/config_';

@Component({
    moduleId: module.id,
	templateUrl: 'widgetConfig-detail.component.html',
	selector: 'widgetConfig-detail',
})
export class WidgetConfigDetailComponent implements OnInit, OnDestroy {
    widgetConfig : WidgetConfig;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new WidgetConfig
    set config(config : Config_) {
        this.widgetConfig = new WidgetConfig();
        this.widgetConfig.config = config;
    }

    @Output() onSaveClicked = new EventEmitter<WidgetConfig>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private widgetConfigService: WidgetConfigService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for widgetConfig-detail ' + id);

            if (id === 'new') {
                this.widgetConfig = new WidgetConfig();
            } else {
                this.widgetConfigService.getWidgetConfig(id)
                    .subscribe(widgetConfig => {
                            this.widgetConfig = widgetConfig;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoConfig() {
        this.router.navigate(['/config_', this.widgetConfig.config.id]);
    }

    clearConfig() {
        this.widgetConfig.config = null;
    }

    onSave() {
        this.widgetConfigService.update(this.widgetConfig).
            subscribe(
                widgetConfig => {
                    this.widgetConfig = widgetConfig;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.widgetConfig);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
