//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { User_ } from './user_';

@Injectable()
export class User_Service {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a User_ by id.
     */
    getUser_(id : any) : Observable<User_> {
        return this.http.get('/api/user_s/' + id)
            .map(response => new User_(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed user_.
     */
    update(user_ : User_) : Observable<User_> {
        let body = JSON.stringify(user_);

        return this.http.put('/api/user_s/', body, this.options)
            .map(response => new User_(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of User_ using the passed
     * user_ as an example for the search by example facility.
     */
    getPage(user_ : User_, event : LazyLoadEvent) : Observable<PageResponse<User_>> {
        let req = new PageRequestByExample(user_, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/user_s/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<User_>(pr.totalPages, pr.totalElements, User_.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by User_CompleteComponent.
     */
    complete(query : string) : Observable<User_[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/user_s/complete', body, this.options)
            .map(response => User_.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an User_ by id.
     */
    delete(id : any) {
        return this.http.delete('/api/user_s/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
