//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import {Component, EventEmitter, Input, Output, SimpleChanges} from '@angular/core';
import {Router} from '@angular/router';
import {DataTable, LazyLoadEvent} from 'primeng/primeng';
import {PageResponse} from "../../support/paging";
import {MessageService} from '../../service/message.service';
import {MatDialog} from '@angular/material';
import {ConfirmDeleteDialogComponent} from "../../support/confirm-delete-dialog.component";
import {User_} from './user_';
import {User_Service} from './user_.service';

@Component({
    moduleId: module.id,
	templateUrl: 'user_-list.component.html',
	selector: 'user_-list'
})
export class User_ListComponent {

    @Input() header = "User_s...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    user_ToDelete : User_;

    // basic search criterias (visible if not in 'sub' mode)
    example : User_ = new User_();

    // list is paginated
    currentPage : PageResponse<User_> = new PageResponse<User_>(0,0,[]);


    constructor(private router : Router,
        private user_Service : User_Service,
        private messageService : MessageService,
        private confirmDeleteDialog: MatDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.user_Service.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/user_', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/user_', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let user_ToDelete : User_ = <User_> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(user_ToDelete);
            }
        });
    }

    private delete(user_ToDelete : User_) {
        let id =  user_ToDelete.id;

        this.user_Service.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(user_ToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}