//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import {Component, EventEmitter, Input, Output, SimpleChanges} from '@angular/core';
import {Router} from '@angular/router';
import {DataTable, LazyLoadEvent} from 'primeng/primeng';
import {PageResponse} from "../../support/paging";
import {MessageService} from '../../service/message.service';
import {MatDialog} from '@angular/material';
import {ConfirmDeleteDialogComponent} from "../../support/confirm-delete-dialog.component";
import {App_} from './app_';
import {App_Service} from './app_.service';

@Component({
    moduleId: module.id,
	templateUrl: 'app_-list.component.html',
	selector: 'app_-list'
})
export class App_ListComponent {

    @Input() header = "App_s...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    app_ToDelete : App_;

    // basic search criterias (visible if not in 'sub' mode)
    example : App_ = new App_();

    // list is paginated
    currentPage : PageResponse<App_> = new PageResponse<App_>(0,0,[]);


    constructor(private router : Router,
        private app_Service : App_Service,
        private messageService : MessageService,
        private confirmDeleteDialog: MatDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.app_Service.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/app_', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/app_', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let app_ToDelete : App_ = <App_> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(app_ToDelete);
            }
        });
    }

    private delete(app_ToDelete : App_) {
        let id =  app_ToDelete.id;

        this.app_Service.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(app_ToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}