/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.willbe.giftapp.rest;

import com.willbe.giftapp.dto.App_DTO;
import com.willbe.giftapp.dto.App_DTOService;
import com.willbe.giftapp.dto.support.PageRequestByExample;
import com.willbe.giftapp.dto.support.PageResponse;
import com.willbe.giftapp.repository.App_Repository;
import com.willbe.giftapp.rest.support.AutoCompleteQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.inject.Inject;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

@RestController
@RequestMapping("/api/app_s")
public class App_Resource {

    private final Logger log = LoggerFactory.getLogger(App_Resource.class);

    @Inject
    private App_Repository app_Repository;
    @Inject
    private App_DTOService app_DTOService;

    /**
     * Create a new App_.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<App_DTO> create(@RequestBody App_DTO app_DTO) throws URISyntaxException {

        log.debug("Create App_DTO : {}", app_DTO);

        if (app_DTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create App_ with existing ID").body(null);
        }

        App_DTO result = app_DTOService.save(app_DTO);

        return ResponseEntity.created(new URI("/api/app_s/" + result.id)).body(result);
    }

    /**
    * Find by id App_.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<App_DTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id App_ : {}", id);

        return Optional.ofNullable(app_DTOService.findOne(id)).map(app_DTO -> new ResponseEntity<>(app_DTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update App_.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<App_DTO> update(@RequestBody App_DTO app_DTO) throws URISyntaxException {

        log.debug("Update App_DTO : {}", app_DTO);

        if (!app_DTO.isIdSet()) {
            return create(app_DTO);
        }

        App_DTO result = app_DTOService.save(app_DTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of App_ using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<App_DTO>> findAll(@RequestBody PageRequestByExample<App_DTO> prbe) throws URISyntaxException {
        PageResponse<App_DTO> pageResponse = app_DTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<App_DTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<App_DTO> results = app_DTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id App_.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id App_ : {}", id);

        try {
            app_Repository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}