/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.willbe.giftapp.rest;

import com.willbe.giftapp.dto.ArtifactDTO;
import com.willbe.giftapp.dto.ArtifactDTOService;
import com.willbe.giftapp.dto.support.PageRequestByExample;
import com.willbe.giftapp.dto.support.PageResponse;
import com.willbe.giftapp.repository.ArtifactRepository;
import com.willbe.giftapp.rest.support.AutoCompleteQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.inject.Inject;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

@RestController
@RequestMapping("/api/artifacts")
public class ArtifactResource {

    private final Logger log = LoggerFactory.getLogger(ArtifactResource.class);

    @Inject
    private ArtifactRepository artifactRepository;
    @Inject
    private ArtifactDTOService artifactDTOService;

    /**
     * Create a new Artifact.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ArtifactDTO> create(@RequestBody ArtifactDTO artifactDTO) throws URISyntaxException {

        log.debug("Create ArtifactDTO : {}", artifactDTO);

        if (artifactDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Artifact with existing ID").body(null);
        }

        ArtifactDTO result = artifactDTOService.save(artifactDTO);

        return ResponseEntity.created(new URI("/api/artifacts/" + result.id)).body(result);
    }

    /**
    * Find by id Artifact.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ArtifactDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Artifact : {}", id);

        return Optional.ofNullable(artifactDTOService.findOne(id)).map(artifactDTO -> new ResponseEntity<>(artifactDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Artifact.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<ArtifactDTO> update(@RequestBody ArtifactDTO artifactDTO) throws URISyntaxException {

        log.debug("Update ArtifactDTO : {}", artifactDTO);

        if (!artifactDTO.isIdSet()) {
            return create(artifactDTO);
        }

        ArtifactDTO result = artifactDTOService.save(artifactDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Artifact using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<ArtifactDTO>> findAll(@RequestBody PageRequestByExample<ArtifactDTO> prbe) throws URISyntaxException {
        PageResponse<ArtifactDTO> pageResponse = artifactDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<ArtifactDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<ArtifactDTO> results = artifactDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Artifact.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Artifact : {}", id);

        try {
            artifactRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}