/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.willbe.giftapp.rest;

import com.willbe.giftapp.dto.Config_DTO;
import com.willbe.giftapp.dto.Config_DTOService;
import com.willbe.giftapp.dto.support.PageRequestByExample;
import com.willbe.giftapp.dto.support.PageResponse;
import com.willbe.giftapp.repository.Config_Repository;
import com.willbe.giftapp.rest.support.AutoCompleteQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.inject.Inject;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

@RestController
@RequestMapping("/api/config_s")
public class Config_Resource {

    private final Logger log = LoggerFactory.getLogger(Config_Resource.class);

    @Inject
    private Config_Repository config_Repository;
    @Inject
    private Config_DTOService config_DTOService;

    /**
     * Create a new Config_.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Config_DTO> create(@RequestBody Config_DTO config_DTO) throws URISyntaxException {

        log.debug("Create Config_DTO : {}", config_DTO);

        if (config_DTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Config_ with existing ID").body(null);
        }

        Config_DTO result = config_DTOService.save(config_DTO);

        return ResponseEntity.created(new URI("/api/config_s/" + result.id)).body(result);
    }

    /**
    * Find by id Config_.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Config_DTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Config_ : {}", id);

        return Optional.ofNullable(config_DTOService.findOne(id)).map(config_DTO -> new ResponseEntity<>(config_DTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Config_.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Config_DTO> update(@RequestBody Config_DTO config_DTO) throws URISyntaxException {

        log.debug("Update Config_DTO : {}", config_DTO);

        if (!config_DTO.isIdSet()) {
            return create(config_DTO);
        }

        Config_DTO result = config_DTOService.save(config_DTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Config_ using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<Config_DTO>> findAll(@RequestBody PageRequestByExample<Config_DTO> prbe) throws URISyntaxException {
        PageResponse<Config_DTO> pageResponse = config_DTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<Config_DTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<Config_DTO> results = config_DTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Config_.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Config_ : {}", id);

        try {
            config_Repository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}