/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.willbe.giftapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.willbe.giftapp.domain.User_;
import com.willbe.giftapp.dto.User_DTO;
import com.willbe.giftapp.dto.User_DTOService;
import com.willbe.giftapp.dto.support.PageRequestByExample;
import com.willbe.giftapp.dto.support.PageResponse;
import com.willbe.giftapp.repository.User_Repository;
import com.willbe.giftapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/user_s")
public class User_Resource {

    private final Logger log = LoggerFactory.getLogger(User_Resource.class);

    @Inject
    private User_Repository user_Repository;
    @Inject
    private User_DTOService user_DTOService;

    /**
     * Create a new User_.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<User_DTO> create(@RequestBody User_DTO user_DTO) throws URISyntaxException {

        log.debug("Create User_DTO : {}", user_DTO);

        if (user_DTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create User_ with existing ID").body(null);
        }

        User_DTO result = user_DTOService.save(user_DTO);

        return ResponseEntity.created(new URI("/api/user_s/" + result.id)).body(result);
    }

    /**
    * Find by id User_.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<User_DTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id User_ : {}", id);

        return Optional.ofNullable(user_DTOService.findOne(id)).map(user_DTO -> new ResponseEntity<>(user_DTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update User_.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<User_DTO> update(@RequestBody User_DTO user_DTO) throws URISyntaxException {

        log.debug("Update User_DTO : {}", user_DTO);

        if (!user_DTO.isIdSet()) {
            return create(user_DTO);
        }

        User_DTO result = user_DTOService.save(user_DTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of User_ using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<User_DTO>> findAll(@RequestBody PageRequestByExample<User_DTO> prbe) throws URISyntaxException {
        PageResponse<User_DTO> pageResponse = user_DTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<User_DTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<User_DTO> results = user_DTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id User_.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id User_ : {}", id);

        try {
            user_Repository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}