/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.willbe.giftapp.rest;

import com.willbe.giftapp.dto.WidgetConfigDTO;
import com.willbe.giftapp.dto.WidgetConfigDTOService;
import com.willbe.giftapp.dto.support.PageRequestByExample;
import com.willbe.giftapp.dto.support.PageResponse;
import com.willbe.giftapp.repository.WidgetConfigRepository;
import com.willbe.giftapp.rest.support.AutoCompleteQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.inject.Inject;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

@RestController
@RequestMapping("/api/widgetConfigs")
public class WidgetConfigResource {

    private final Logger log = LoggerFactory.getLogger(WidgetConfigResource.class);

    @Inject
    private WidgetConfigRepository widgetConfigRepository;
    @Inject
    private WidgetConfigDTOService widgetConfigDTOService;

    /**
     * Create a new WidgetConfig.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WidgetConfigDTO> create(@RequestBody WidgetConfigDTO widgetConfigDTO) throws URISyntaxException {

        log.debug("Create WidgetConfigDTO : {}", widgetConfigDTO);

        if (widgetConfigDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create WidgetConfig with existing ID").body(null);
        }

        WidgetConfigDTO result = widgetConfigDTOService.save(widgetConfigDTO);

        return ResponseEntity.created(new URI("/api/widgetConfigs/" + result.id)).body(result);
    }

    /**
    * Find by id WidgetConfig.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WidgetConfigDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id WidgetConfig : {}", id);

        return Optional.ofNullable(widgetConfigDTOService.findOne(id)).map(widgetConfigDTO -> new ResponseEntity<>(widgetConfigDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update WidgetConfig.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WidgetConfigDTO> update(@RequestBody WidgetConfigDTO widgetConfigDTO) throws URISyntaxException {

        log.debug("Update WidgetConfigDTO : {}", widgetConfigDTO);

        if (!widgetConfigDTO.isIdSet()) {
            return create(widgetConfigDTO);
        }

        WidgetConfigDTO result = widgetConfigDTOService.save(widgetConfigDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of WidgetConfig using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<WidgetConfigDTO>> findAll(@RequestBody PageRequestByExample<WidgetConfigDTO> prbe) throws URISyntaxException {
        PageResponse<WidgetConfigDTO> pageResponse = widgetConfigDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<WidgetConfigDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<WidgetConfigDTO> results = widgetConfigDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id WidgetConfig.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id WidgetConfig : {}", id);

        try {
            widgetConfigRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}