//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Config_} from '../config_/config_';
import {User_} from '../user_/user_';
import {App_} from '../app_/app_';

export class Artifact {
    // Raw attributes
    id : number;
    outputPath : string;
    // x-to-one
    config : Config_;
    user : User_;
    app : App_;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.outputPath = json.outputPath;

            if (json.config != null) {
                this.config = new Config_(json.config);
            }

            if (json.user != null) {
                this.user = new User_(json.user);
            }

            if (json.app != null) {
                this.app = new App_(json.app);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Artifact[] {
        let artifacts : Artifact[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                artifacts.push(new Artifact(json));
            }
        }
        return artifacts;
    }
}
